name: Standard CI

#Trigger
on: push

jobs: 
  build-test:
    name: Build test and deploy
    runs-on: ubuntu@latest

    steps: 
      - name: Checkout latest code 
        uses: actions/checkout@v4
      - name: Set up Nodejs
        uses: actions/setup-node@v4 
      - name: Run lint
        run:  npm run lint
      - name: Run tests
        run: npm run test
      - name: Run deploy
        runs: npm run deploy

